# Generated by Django 3.1.2 on 2020-11-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201123_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='attach',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homework',
            name='commit_date',
            field=models.DateField(auto_now=True),
        ),
    ]
